//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.12

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

part of ory_api_client;

class OAuth2Client {
  /// Returns a new [OAuth2Client] instance.
  OAuth2Client({
    this.allowedCorsOrigins = const [],
    this.audience = const [],
    this.authorizationCodeGrantAccessTokenLifespan,
    this.authorizationCodeGrantIdTokenLifespan,
    this.authorizationCodeGrantRefreshTokenLifespan,
    this.backchannelLogoutSessionRequired,
    this.backchannelLogoutUri,
    this.clientCredentialsGrantAccessTokenLifespan,
    this.clientId,
    this.clientName,
    this.clientSecret,
    this.clientSecretExpiresAt,
    this.clientUri,
    this.contacts = const [],
    this.createdAt,
    this.frontchannelLogoutSessionRequired,
    this.frontchannelLogoutUri,
    this.grantTypes = const [],
    this.implicitGrantAccessTokenLifespan,
    this.implicitGrantIdTokenLifespan,
    this.jwks,
    this.jwksUri,
    this.jwtBearerGrantAccessTokenLifespan,
    this.logoUri,
    this.metadata,
    this.owner,
    this.policyUri,
    this.postLogoutRedirectUris = const [],
    this.redirectUris = const [],
    this.refreshTokenGrantAccessTokenLifespan,
    this.refreshTokenGrantIdTokenLifespan,
    this.refreshTokenGrantRefreshTokenLifespan,
    this.registrationAccessToken,
    this.registrationClientUri,
    this.requestObjectSigningAlg,
    this.requestUris = const [],
    this.responseTypes = const [],
    this.scope,
    this.sectorIdentifierUri,
    this.subjectType,
    this.tokenEndpointAuthMethod,
    this.tokenEndpointAuthSigningAlg,
    this.tosUri,
    this.updatedAt,
    this.userinfoSignedResponseAlg,
  });

  List<String> allowedCorsOrigins;

  List<String> audience;

  String? authorizationCodeGrantAccessTokenLifespan;

  String? authorizationCodeGrantIdTokenLifespan;

  String? authorizationCodeGrantRefreshTokenLifespan;

  /// OpenID Connect Back-Channel Logout Session Required  Boolean value specifying whether the RP requires that a sid (session ID) Claim be included in the Logout Token to identify the RP session with the OP when the backchannel_logout_uri is used. If omitted, the default value is false.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  bool? backchannelLogoutSessionRequired;

  /// OpenID Connect Back-Channel Logout URI  RP URL that will cause the RP to log itself out when sent a Logout Token by the OP.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? backchannelLogoutUri;

  String? clientCredentialsGrantAccessTokenLifespan;

  /// OAuth 2.0 Client ID  The ID is autogenerated and immutable.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? clientId;

  /// OAuth 2.0 Client Name  The human-readable name of the client to be presented to the end-user during authorization.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? clientName;

  /// OAuth 2.0 Client Secret  The secret will be included in the create request as cleartext, and then never again. The secret is kept in hashed format and is not recoverable once lost.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? clientSecret;

  /// OAuth 2.0 Client Secret Expires At  The field is currently not supported and its value is always 0.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  int? clientSecretExpiresAt;

  /// OAuth 2.0 Client URI  ClientURI is a URL string of a web page providing information about the client. If present, the server SHOULD display this URL to the end-user in a clickable fashion.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? clientUri;

  List<String> contacts;

  /// OAuth 2.0 Client Creation Date  CreatedAt returns the timestamp of the client's creation.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  DateTime? createdAt;

  /// OpenID Connect Front-Channel Logout Session Required  Boolean value specifying whether the RP requires that iss (issuer) and sid (session ID) query parameters be included to identify the RP session with the OP when the frontchannel_logout_uri is used. If omitted, the default value is false.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  bool? frontchannelLogoutSessionRequired;

  /// OpenID Connect Front-Channel Logout URI  RP URL that will cause the RP to log itself out when rendered in an iframe by the OP. An iss (issuer) query parameter and a sid (session ID) query parameter MAY be included by the OP to enable the RP to validate the request and to determine which of the potentially multiple sessions is to be logged out; if either is included, both MUST be.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? frontchannelLogoutUri;

  List<String> grantTypes;

  String? implicitGrantAccessTokenLifespan;

  String? implicitGrantIdTokenLifespan;

  /// OAuth 2.0 Client JSON Web Key Set  Client's JSON Web Key Set [JWK] document, passed by value. The semantics of the jwks parameter are the same as the jwks_uri parameter, other than that the JWK Set is passed by value, rather than by reference. This parameter is intended only to be used by Clients that, for some reason, are unable to use the jwks_uri parameter, for instance, by native applications that might not have a location to host the contents of the JWK Set. If a Client can use jwks_uri, it MUST NOT use jwks. One significant downside of jwks is that it does not enable key rotation (which jwks_uri does, as described in Section 10 of OpenID Connect Core 1.0 [OpenID.Core]). The jwks_uri and jwks parameters MUST NOT be used together.
  Object? jwks;

  /// OAuth 2.0 Client JSON Web Key Set URL  URL for the Client's JSON Web Key Set [JWK] document. If the Client signs requests to the Server, it contains the signing key(s) the Server uses to validate signatures from the Client. The JWK Set MAY also contain the Client's encryption keys(s), which are used by the Server to encrypt responses to the Client. When both signing and encryption keys are made available, a use (Key Use) parameter value is REQUIRED for all keys in the referenced JWK Set to indicate each key's intended usage. Although some algorithms allow the same key to be used for both signatures and encryption, doing so is NOT RECOMMENDED, as it is less secure. The JWK x5c parameter MAY be used to provide X.509 representations of keys provided. When used, the bare key values MUST still be present and MUST match those in the certificate.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? jwksUri;

  String? jwtBearerGrantAccessTokenLifespan;

  /// OAuth 2.0 Client Logo URI  A URL string referencing the client's logo.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? logoUri;

  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  Object? metadata;

  /// OAuth 2.0 Client Owner  Owner is a string identifying the owner of the OAuth 2.0 Client.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? owner;

  /// OAuth 2.0 Client Policy URI  PolicyURI is a URL string that points to a human-readable privacy policy document that describes how the deployment organization collects, uses, retains, and discloses personal data.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? policyUri;

  List<String> postLogoutRedirectUris;

  List<String> redirectUris;

  String? refreshTokenGrantAccessTokenLifespan;

  String? refreshTokenGrantIdTokenLifespan;

  String? refreshTokenGrantRefreshTokenLifespan;

  /// OpenID Connect Dynamic Client Registration Access Token  RegistrationAccessToken can be used to update, get, or delete the OAuth2 Client. It is sent when creating a client using Dynamic Client Registration.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? registrationAccessToken;

  /// OpenID Connect Dynamic Client Registration URL  RegistrationClientURI is the URL used to update, get, or delete the OAuth2 Client.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? registrationClientUri;

  /// OpenID Connect Request Object Signing Algorithm  JWS [JWS] alg algorithm [JWA] that MUST be used for signing Request Objects sent to the OP. All Request Objects from this Client MUST be rejected, if not signed with this algorithm.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? requestObjectSigningAlg;

  List<String> requestUris;

  List<String> responseTypes;

  /// OAuth 2.0 Client Scope  Scope is a string containing a space-separated list of scope values (as described in Section 3.3 of OAuth 2.0 [RFC6749]) that the client can use when requesting access tokens.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? scope;

  /// OpenID Connect Sector Identifier URI  URL using the https scheme to be used in calculating Pseudonymous Identifiers by the OP. The URL references a file with a single JSON array of redirect_uri values.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? sectorIdentifierUri;

  /// OpenID Connect Subject Type  The `subject_types_supported` Discovery parameter contains a list of the supported subject_type values for this server. Valid types include `pairwise` and `public`.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? subjectType;

  /// OAuth 2.0 Token Endpoint Authentication Method  Requested Client Authentication method for the Token Endpoint. The options are:  `client_secret_post`: (default) Send `client_id` and `client_secret` as `application/x-www-form-urlencoded` in the HTTP body. `client_secret_basic`: Send `client_id` and `client_secret` as `application/x-www-form-urlencoded` encoded in the HTTP Authorization header. `private_key_jwt`: Use JSON Web Tokens to authenticate the client. `none`: Used for public clients (native apps, mobile apps) which can not have secrets.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? tokenEndpointAuthMethod;

  /// OAuth 2.0 Token Endpoint Signing Algorithm  Requested Client Authentication signing algorithm for the Token Endpoint.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? tokenEndpointAuthSigningAlg;

  /// OAuth 2.0 Client Terms of Service URI  A URL string pointing to a human-readable terms of service document for the client that describes a contractual relationship between the end-user and the client that the end-user accepts when authorizing the client.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? tosUri;

  /// OAuth 2.0 Client Last Update Date  UpdatedAt returns the timestamp of the last update.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  DateTime? updatedAt;

  /// OpenID Connect Request Userinfo Signed Response Algorithm  JWS alg algorithm [JWA] REQUIRED for signing UserInfo Responses. If this is specified, the response will be JWT [JWT] serialized, and signed using JWS. The default, if omitted, is for the UserInfo Response to return the Claims as a UTF-8 encoded JSON object using the application/json content-type.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? userinfoSignedResponseAlg;

  @override
  bool operator ==(Object other) => identical(this, other) || other is OAuth2Client &&
     other.allowedCorsOrigins == allowedCorsOrigins &&
     other.audience == audience &&
     other.authorizationCodeGrantAccessTokenLifespan == authorizationCodeGrantAccessTokenLifespan &&
     other.authorizationCodeGrantIdTokenLifespan == authorizationCodeGrantIdTokenLifespan &&
     other.authorizationCodeGrantRefreshTokenLifespan == authorizationCodeGrantRefreshTokenLifespan &&
     other.backchannelLogoutSessionRequired == backchannelLogoutSessionRequired &&
     other.backchannelLogoutUri == backchannelLogoutUri &&
     other.clientCredentialsGrantAccessTokenLifespan == clientCredentialsGrantAccessTokenLifespan &&
     other.clientId == clientId &&
     other.clientName == clientName &&
     other.clientSecret == clientSecret &&
     other.clientSecretExpiresAt == clientSecretExpiresAt &&
     other.clientUri == clientUri &&
     other.contacts == contacts &&
     other.createdAt == createdAt &&
     other.frontchannelLogoutSessionRequired == frontchannelLogoutSessionRequired &&
     other.frontchannelLogoutUri == frontchannelLogoutUri &&
     other.grantTypes == grantTypes &&
     other.implicitGrantAccessTokenLifespan == implicitGrantAccessTokenLifespan &&
     other.implicitGrantIdTokenLifespan == implicitGrantIdTokenLifespan &&
     other.jwks == jwks &&
     other.jwksUri == jwksUri &&
     other.jwtBearerGrantAccessTokenLifespan == jwtBearerGrantAccessTokenLifespan &&
     other.logoUri == logoUri &&
     other.metadata == metadata &&
     other.owner == owner &&
     other.policyUri == policyUri &&
     other.postLogoutRedirectUris == postLogoutRedirectUris &&
     other.redirectUris == redirectUris &&
     other.refreshTokenGrantAccessTokenLifespan == refreshTokenGrantAccessTokenLifespan &&
     other.refreshTokenGrantIdTokenLifespan == refreshTokenGrantIdTokenLifespan &&
     other.refreshTokenGrantRefreshTokenLifespan == refreshTokenGrantRefreshTokenLifespan &&
     other.registrationAccessToken == registrationAccessToken &&
     other.registrationClientUri == registrationClientUri &&
     other.requestObjectSigningAlg == requestObjectSigningAlg &&
     other.requestUris == requestUris &&
     other.responseTypes == responseTypes &&
     other.scope == scope &&
     other.sectorIdentifierUri == sectorIdentifierUri &&
     other.subjectType == subjectType &&
     other.tokenEndpointAuthMethod == tokenEndpointAuthMethod &&
     other.tokenEndpointAuthSigningAlg == tokenEndpointAuthSigningAlg &&
     other.tosUri == tosUri &&
     other.updatedAt == updatedAt &&
     other.userinfoSignedResponseAlg == userinfoSignedResponseAlg;

  @override
  int get hashCode =>
    // ignore: unnecessary_parenthesis
    (allowedCorsOrigins.hashCode) +
    (audience.hashCode) +
    (authorizationCodeGrantAccessTokenLifespan == null ? 0 : authorizationCodeGrantAccessTokenLifespan!.hashCode) +
    (authorizationCodeGrantIdTokenLifespan == null ? 0 : authorizationCodeGrantIdTokenLifespan!.hashCode) +
    (authorizationCodeGrantRefreshTokenLifespan == null ? 0 : authorizationCodeGrantRefreshTokenLifespan!.hashCode) +
    (backchannelLogoutSessionRequired == null ? 0 : backchannelLogoutSessionRequired!.hashCode) +
    (backchannelLogoutUri == null ? 0 : backchannelLogoutUri!.hashCode) +
    (clientCredentialsGrantAccessTokenLifespan == null ? 0 : clientCredentialsGrantAccessTokenLifespan!.hashCode) +
    (clientId == null ? 0 : clientId!.hashCode) +
    (clientName == null ? 0 : clientName!.hashCode) +
    (clientSecret == null ? 0 : clientSecret!.hashCode) +
    (clientSecretExpiresAt == null ? 0 : clientSecretExpiresAt!.hashCode) +
    (clientUri == null ? 0 : clientUri!.hashCode) +
    (contacts.hashCode) +
    (createdAt == null ? 0 : createdAt!.hashCode) +
    (frontchannelLogoutSessionRequired == null ? 0 : frontchannelLogoutSessionRequired!.hashCode) +
    (frontchannelLogoutUri == null ? 0 : frontchannelLogoutUri!.hashCode) +
    (grantTypes.hashCode) +
    (implicitGrantAccessTokenLifespan == null ? 0 : implicitGrantAccessTokenLifespan!.hashCode) +
    (implicitGrantIdTokenLifespan == null ? 0 : implicitGrantIdTokenLifespan!.hashCode) +
    (jwks == null ? 0 : jwks!.hashCode) +
    (jwksUri == null ? 0 : jwksUri!.hashCode) +
    (jwtBearerGrantAccessTokenLifespan == null ? 0 : jwtBearerGrantAccessTokenLifespan!.hashCode) +
    (logoUri == null ? 0 : logoUri!.hashCode) +
    (metadata == null ? 0 : metadata!.hashCode) +
    (owner == null ? 0 : owner!.hashCode) +
    (policyUri == null ? 0 : policyUri!.hashCode) +
    (postLogoutRedirectUris.hashCode) +
    (redirectUris.hashCode) +
    (refreshTokenGrantAccessTokenLifespan == null ? 0 : refreshTokenGrantAccessTokenLifespan!.hashCode) +
    (refreshTokenGrantIdTokenLifespan == null ? 0 : refreshTokenGrantIdTokenLifespan!.hashCode) +
    (refreshTokenGrantRefreshTokenLifespan == null ? 0 : refreshTokenGrantRefreshTokenLifespan!.hashCode) +
    (registrationAccessToken == null ? 0 : registrationAccessToken!.hashCode) +
    (registrationClientUri == null ? 0 : registrationClientUri!.hashCode) +
    (requestObjectSigningAlg == null ? 0 : requestObjectSigningAlg!.hashCode) +
    (requestUris.hashCode) +
    (responseTypes.hashCode) +
    (scope == null ? 0 : scope!.hashCode) +
    (sectorIdentifierUri == null ? 0 : sectorIdentifierUri!.hashCode) +
    (subjectType == null ? 0 : subjectType!.hashCode) +
    (tokenEndpointAuthMethod == null ? 0 : tokenEndpointAuthMethod!.hashCode) +
    (tokenEndpointAuthSigningAlg == null ? 0 : tokenEndpointAuthSigningAlg!.hashCode) +
    (tosUri == null ? 0 : tosUri!.hashCode) +
    (updatedAt == null ? 0 : updatedAt!.hashCode) +
    (userinfoSignedResponseAlg == null ? 0 : userinfoSignedResponseAlg!.hashCode);

  @override
  String toString() => 'OAuth2Client[allowedCorsOrigins=$allowedCorsOrigins, audience=$audience, authorizationCodeGrantAccessTokenLifespan=$authorizationCodeGrantAccessTokenLifespan, authorizationCodeGrantIdTokenLifespan=$authorizationCodeGrantIdTokenLifespan, authorizationCodeGrantRefreshTokenLifespan=$authorizationCodeGrantRefreshTokenLifespan, backchannelLogoutSessionRequired=$backchannelLogoutSessionRequired, backchannelLogoutUri=$backchannelLogoutUri, clientCredentialsGrantAccessTokenLifespan=$clientCredentialsGrantAccessTokenLifespan, clientId=$clientId, clientName=$clientName, clientSecret=$clientSecret, clientSecretExpiresAt=$clientSecretExpiresAt, clientUri=$clientUri, contacts=$contacts, createdAt=$createdAt, frontchannelLogoutSessionRequired=$frontchannelLogoutSessionRequired, frontchannelLogoutUri=$frontchannelLogoutUri, grantTypes=$grantTypes, implicitGrantAccessTokenLifespan=$implicitGrantAccessTokenLifespan, implicitGrantIdTokenLifespan=$implicitGrantIdTokenLifespan, jwks=$jwks, jwksUri=$jwksUri, jwtBearerGrantAccessTokenLifespan=$jwtBearerGrantAccessTokenLifespan, logoUri=$logoUri, metadata=$metadata, owner=$owner, policyUri=$policyUri, postLogoutRedirectUris=$postLogoutRedirectUris, redirectUris=$redirectUris, refreshTokenGrantAccessTokenLifespan=$refreshTokenGrantAccessTokenLifespan, refreshTokenGrantIdTokenLifespan=$refreshTokenGrantIdTokenLifespan, refreshTokenGrantRefreshTokenLifespan=$refreshTokenGrantRefreshTokenLifespan, registrationAccessToken=$registrationAccessToken, registrationClientUri=$registrationClientUri, requestObjectSigningAlg=$requestObjectSigningAlg, requestUris=$requestUris, responseTypes=$responseTypes, scope=$scope, sectorIdentifierUri=$sectorIdentifierUri, subjectType=$subjectType, tokenEndpointAuthMethod=$tokenEndpointAuthMethod, tokenEndpointAuthSigningAlg=$tokenEndpointAuthSigningAlg, tosUri=$tosUri, updatedAt=$updatedAt, userinfoSignedResponseAlg=$userinfoSignedResponseAlg]';

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
      json[r'allowed_cors_origins'] = this.allowedCorsOrigins;
      json[r'audience'] = this.audience;
    if (this.authorizationCodeGrantAccessTokenLifespan != null) {
      json[r'authorization_code_grant_access_token_lifespan'] = this.authorizationCodeGrantAccessTokenLifespan;
    } else {
      json[r'authorization_code_grant_access_token_lifespan'] = null;
    }
    if (this.authorizationCodeGrantIdTokenLifespan != null) {
      json[r'authorization_code_grant_id_token_lifespan'] = this.authorizationCodeGrantIdTokenLifespan;
    } else {
      json[r'authorization_code_grant_id_token_lifespan'] = null;
    }
    if (this.authorizationCodeGrantRefreshTokenLifespan != null) {
      json[r'authorization_code_grant_refresh_token_lifespan'] = this.authorizationCodeGrantRefreshTokenLifespan;
    } else {
      json[r'authorization_code_grant_refresh_token_lifespan'] = null;
    }
    if (this.backchannelLogoutSessionRequired != null) {
      json[r'backchannel_logout_session_required'] = this.backchannelLogoutSessionRequired;
    } else {
      json[r'backchannel_logout_session_required'] = null;
    }
    if (this.backchannelLogoutUri != null) {
      json[r'backchannel_logout_uri'] = this.backchannelLogoutUri;
    } else {
      json[r'backchannel_logout_uri'] = null;
    }
    if (this.clientCredentialsGrantAccessTokenLifespan != null) {
      json[r'client_credentials_grant_access_token_lifespan'] = this.clientCredentialsGrantAccessTokenLifespan;
    } else {
      json[r'client_credentials_grant_access_token_lifespan'] = null;
    }
    if (this.clientId != null) {
      json[r'client_id'] = this.clientId;
    } else {
      json[r'client_id'] = null;
    }
    if (this.clientName != null) {
      json[r'client_name'] = this.clientName;
    } else {
      json[r'client_name'] = null;
    }
    if (this.clientSecret != null) {
      json[r'client_secret'] = this.clientSecret;
    } else {
      json[r'client_secret'] = null;
    }
    if (this.clientSecretExpiresAt != null) {
      json[r'client_secret_expires_at'] = this.clientSecretExpiresAt;
    } else {
      json[r'client_secret_expires_at'] = null;
    }
    if (this.clientUri != null) {
      json[r'client_uri'] = this.clientUri;
    } else {
      json[r'client_uri'] = null;
    }
      json[r'contacts'] = this.contacts;
    if (this.createdAt != null) {
      json[r'created_at'] = this.createdAt!.toUtc().toIso8601String();
    } else {
      json[r'created_at'] = null;
    }
    if (this.frontchannelLogoutSessionRequired != null) {
      json[r'frontchannel_logout_session_required'] = this.frontchannelLogoutSessionRequired;
    } else {
      json[r'frontchannel_logout_session_required'] = null;
    }
    if (this.frontchannelLogoutUri != null) {
      json[r'frontchannel_logout_uri'] = this.frontchannelLogoutUri;
    } else {
      json[r'frontchannel_logout_uri'] = null;
    }
      json[r'grant_types'] = this.grantTypes;
    if (this.implicitGrantAccessTokenLifespan != null) {
      json[r'implicit_grant_access_token_lifespan'] = this.implicitGrantAccessTokenLifespan;
    } else {
      json[r'implicit_grant_access_token_lifespan'] = null;
    }
    if (this.implicitGrantIdTokenLifespan != null) {
      json[r'implicit_grant_id_token_lifespan'] = this.implicitGrantIdTokenLifespan;
    } else {
      json[r'implicit_grant_id_token_lifespan'] = null;
    }
    if (this.jwks != null) {
      json[r'jwks'] = this.jwks;
    } else {
      json[r'jwks'] = null;
    }
    if (this.jwksUri != null) {
      json[r'jwks_uri'] = this.jwksUri;
    } else {
      json[r'jwks_uri'] = null;
    }
    if (this.jwtBearerGrantAccessTokenLifespan != null) {
      json[r'jwt_bearer_grant_access_token_lifespan'] = this.jwtBearerGrantAccessTokenLifespan;
    } else {
      json[r'jwt_bearer_grant_access_token_lifespan'] = null;
    }
    if (this.logoUri != null) {
      json[r'logo_uri'] = this.logoUri;
    } else {
      json[r'logo_uri'] = null;
    }
    if (this.metadata != null) {
      json[r'metadata'] = this.metadata;
    } else {
      json[r'metadata'] = null;
    }
    if (this.owner != null) {
      json[r'owner'] = this.owner;
    } else {
      json[r'owner'] = null;
    }
    if (this.policyUri != null) {
      json[r'policy_uri'] = this.policyUri;
    } else {
      json[r'policy_uri'] = null;
    }
      json[r'post_logout_redirect_uris'] = this.postLogoutRedirectUris;
      json[r'redirect_uris'] = this.redirectUris;
    if (this.refreshTokenGrantAccessTokenLifespan != null) {
      json[r'refresh_token_grant_access_token_lifespan'] = this.refreshTokenGrantAccessTokenLifespan;
    } else {
      json[r'refresh_token_grant_access_token_lifespan'] = null;
    }
    if (this.refreshTokenGrantIdTokenLifespan != null) {
      json[r'refresh_token_grant_id_token_lifespan'] = this.refreshTokenGrantIdTokenLifespan;
    } else {
      json[r'refresh_token_grant_id_token_lifespan'] = null;
    }
    if (this.refreshTokenGrantRefreshTokenLifespan != null) {
      json[r'refresh_token_grant_refresh_token_lifespan'] = this.refreshTokenGrantRefreshTokenLifespan;
    } else {
      json[r'refresh_token_grant_refresh_token_lifespan'] = null;
    }
    if (this.registrationAccessToken != null) {
      json[r'registration_access_token'] = this.registrationAccessToken;
    } else {
      json[r'registration_access_token'] = null;
    }
    if (this.registrationClientUri != null) {
      json[r'registration_client_uri'] = this.registrationClientUri;
    } else {
      json[r'registration_client_uri'] = null;
    }
    if (this.requestObjectSigningAlg != null) {
      json[r'request_object_signing_alg'] = this.requestObjectSigningAlg;
    } else {
      json[r'request_object_signing_alg'] = null;
    }
      json[r'request_uris'] = this.requestUris;
      json[r'response_types'] = this.responseTypes;
    if (this.scope != null) {
      json[r'scope'] = this.scope;
    } else {
      json[r'scope'] = null;
    }
    if (this.sectorIdentifierUri != null) {
      json[r'sector_identifier_uri'] = this.sectorIdentifierUri;
    } else {
      json[r'sector_identifier_uri'] = null;
    }
    if (this.subjectType != null) {
      json[r'subject_type'] = this.subjectType;
    } else {
      json[r'subject_type'] = null;
    }
    if (this.tokenEndpointAuthMethod != null) {
      json[r'token_endpoint_auth_method'] = this.tokenEndpointAuthMethod;
    } else {
      json[r'token_endpoint_auth_method'] = null;
    }
    if (this.tokenEndpointAuthSigningAlg != null) {
      json[r'token_endpoint_auth_signing_alg'] = this.tokenEndpointAuthSigningAlg;
    } else {
      json[r'token_endpoint_auth_signing_alg'] = null;
    }
    if (this.tosUri != null) {
      json[r'tos_uri'] = this.tosUri;
    } else {
      json[r'tos_uri'] = null;
    }
    if (this.updatedAt != null) {
      json[r'updated_at'] = this.updatedAt!.toUtc().toIso8601String();
    } else {
      json[r'updated_at'] = null;
    }
    if (this.userinfoSignedResponseAlg != null) {
      json[r'userinfo_signed_response_alg'] = this.userinfoSignedResponseAlg;
    } else {
      json[r'userinfo_signed_response_alg'] = null;
    }
    return json;
  }

  /// Returns a new [OAuth2Client] instance and imports its values from
  /// [value] if it's a [Map], null otherwise.
  // ignore: prefer_constructors_over_static_methods
  static OAuth2Client? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      // Ensure that the map contains the required keys.
      // Note 1: the values aren't checked for validity beyond being non-null.
      // Note 2: this code is stripped in release mode!
      assert(() {
        requiredKeys.forEach((key) {
          assert(json.containsKey(key), 'Required key "OAuth2Client[$key]" is missing from JSON.');
          assert(json[key] != null, 'Required key "OAuth2Client[$key]" has a null value in JSON.');
        });
        return true;
      }());

      return OAuth2Client(
        allowedCorsOrigins: json[r'allowed_cors_origins'] is List
            ? (json[r'allowed_cors_origins'] as List).cast<String>()
            : const [],
        audience: json[r'audience'] is List
            ? (json[r'audience'] as List).cast<String>()
            : const [],
        authorizationCodeGrantAccessTokenLifespan: mapValueOfType<String>(json, r'authorization_code_grant_access_token_lifespan'),
        authorizationCodeGrantIdTokenLifespan: mapValueOfType<String>(json, r'authorization_code_grant_id_token_lifespan'),
        authorizationCodeGrantRefreshTokenLifespan: mapValueOfType<String>(json, r'authorization_code_grant_refresh_token_lifespan'),
        backchannelLogoutSessionRequired: mapValueOfType<bool>(json, r'backchannel_logout_session_required'),
        backchannelLogoutUri: mapValueOfType<String>(json, r'backchannel_logout_uri'),
        clientCredentialsGrantAccessTokenLifespan: mapValueOfType<String>(json, r'client_credentials_grant_access_token_lifespan'),
        clientId: mapValueOfType<String>(json, r'client_id'),
        clientName: mapValueOfType<String>(json, r'client_name'),
        clientSecret: mapValueOfType<String>(json, r'client_secret'),
        clientSecretExpiresAt: mapValueOfType<int>(json, r'client_secret_expires_at'),
        clientUri: mapValueOfType<String>(json, r'client_uri'),
        contacts: json[r'contacts'] is List
            ? (json[r'contacts'] as List).cast<String>()
            : const [],
        createdAt: mapDateTime(json, r'created_at', ''),
        frontchannelLogoutSessionRequired: mapValueOfType<bool>(json, r'frontchannel_logout_session_required'),
        frontchannelLogoutUri: mapValueOfType<String>(json, r'frontchannel_logout_uri'),
        grantTypes: json[r'grant_types'] is List
            ? (json[r'grant_types'] as List).cast<String>()
            : const [],
        implicitGrantAccessTokenLifespan: mapValueOfType<String>(json, r'implicit_grant_access_token_lifespan'),
        implicitGrantIdTokenLifespan: mapValueOfType<String>(json, r'implicit_grant_id_token_lifespan'),
        jwks: mapValueOfType<Object>(json, r'jwks'),
        jwksUri: mapValueOfType<String>(json, r'jwks_uri'),
        jwtBearerGrantAccessTokenLifespan: mapValueOfType<String>(json, r'jwt_bearer_grant_access_token_lifespan'),
        logoUri: mapValueOfType<String>(json, r'logo_uri'),
        metadata: mapValueOfType<Object>(json, r'metadata'),
        owner: mapValueOfType<String>(json, r'owner'),
        policyUri: mapValueOfType<String>(json, r'policy_uri'),
        postLogoutRedirectUris: json[r'post_logout_redirect_uris'] is List
            ? (json[r'post_logout_redirect_uris'] as List).cast<String>()
            : const [],
        redirectUris: json[r'redirect_uris'] is List
            ? (json[r'redirect_uris'] as List).cast<String>()
            : const [],
        refreshTokenGrantAccessTokenLifespan: mapValueOfType<String>(json, r'refresh_token_grant_access_token_lifespan'),
        refreshTokenGrantIdTokenLifespan: mapValueOfType<String>(json, r'refresh_token_grant_id_token_lifespan'),
        refreshTokenGrantRefreshTokenLifespan: mapValueOfType<String>(json, r'refresh_token_grant_refresh_token_lifespan'),
        registrationAccessToken: mapValueOfType<String>(json, r'registration_access_token'),
        registrationClientUri: mapValueOfType<String>(json, r'registration_client_uri'),
        requestObjectSigningAlg: mapValueOfType<String>(json, r'request_object_signing_alg'),
        requestUris: json[r'request_uris'] is List
            ? (json[r'request_uris'] as List).cast<String>()
            : const [],
        responseTypes: json[r'response_types'] is List
            ? (json[r'response_types'] as List).cast<String>()
            : const [],
        scope: mapValueOfType<String>(json, r'scope'),
        sectorIdentifierUri: mapValueOfType<String>(json, r'sector_identifier_uri'),
        subjectType: mapValueOfType<String>(json, r'subject_type'),
        tokenEndpointAuthMethod: mapValueOfType<String>(json, r'token_endpoint_auth_method'),
        tokenEndpointAuthSigningAlg: mapValueOfType<String>(json, r'token_endpoint_auth_signing_alg'),
        tosUri: mapValueOfType<String>(json, r'tos_uri'),
        updatedAt: mapDateTime(json, r'updated_at', ''),
        userinfoSignedResponseAlg: mapValueOfType<String>(json, r'userinfo_signed_response_alg'),
      );
    }
    return null;
  }

  static List<OAuth2Client>? listFromJson(dynamic json, {bool growable = false,}) {
    final result = <OAuth2Client>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = OAuth2Client.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  static Map<String, OAuth2Client> mapFromJson(dynamic json) {
    final map = <String, OAuth2Client>{};
    if (json is Map && json.isNotEmpty) {
      json = json.cast<String, dynamic>(); // ignore: parameter_assignments
      for (final entry in json.entries) {
        final value = OAuth2Client.fromJson(entry.value);
        if (value != null) {
          map[entry.key] = value;
        }
      }
    }
    return map;
  }

  // maps a json object with a list of OAuth2Client-objects as value to a dart map
  static Map<String, List<OAuth2Client>> mapListFromJson(dynamic json, {bool growable = false,}) {
    final map = <String, List<OAuth2Client>>{};
    if (json is Map && json.isNotEmpty) {
      json = json.cast<String, dynamic>(); // ignore: parameter_assignments
      for (final entry in json.entries) {
        final value = OAuth2Client.listFromJson(entry.value, growable: growable,);
        if (value != null) {
          map[entry.key] = value;
        }
      }
    }
    return map;
  }

  /// The list of required keys that must be present in a JSON.
  static const requiredKeys = <String>{
  };
}

