name: user_repo
description: A package to interact with the current user.
publish_to: "none"
version: 0.0.1
homepage: x

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  http: ">=0.13.0 <0.14.0"
  ory_api_client:
    path: ../ory_api_client
  url_launcher: ^6.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
