name: mattgonewild.com
description: The web UI for mattgonewild.com.
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  user_repo:
    path: pkg/user_repo
  ory_api_client:
    path: pkg/ory_api_client

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
