//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.12

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

library ory_api_client;

import 'dart:async';
import 'dart:convert';
import 'dart:html';

import 'package:http/browser_client.dart';
import 'package:http/http.dart';
import 'package:intl/intl.dart';
import 'package:meta/meta.dart';

part 'api_client.dart';
part 'api_helper.dart';
part 'api_exception.dart';
part 'auth/authentication.dart';
part 'auth/api_key_auth.dart';
part 'auth/oauth.dart';
part 'auth/http_basic_auth.dart';
part 'auth/http_bearer_auth.dart';

part 'api/courier_api.dart';
part 'api/frontend_api.dart';
part 'api/identity_api.dart';
part 'api/jwk_api.dart';
part 'api/metadata_api.dart';
part 'api/o_auth2_api.dart';
part 'api/oidc_api.dart';
part 'api/permission_api.dart';
part 'api/project_api.dart';
part 'api/relationship_api.dart';
part 'api/wellknown_api.dart';

part 'model/accept_o_auth2_consent_request.dart';
part 'model/accept_o_auth2_consent_request_session.dart';
part 'model/accept_o_auth2_login_request.dart';
part 'model/active_project_in_console.dart';
part 'model/authenticator_assurance_level.dart';
part 'model/check_opl_syntax_result.dart';
part 'model/check_permission_result.dart';
part 'model/cloud_account.dart';
part 'model/courier_message_status.dart';
part 'model/courier_message_type.dart';
part 'model/create_custom_domain_body.dart';
part 'model/create_identity_body.dart';
part 'model/create_json_web_key_set.dart';
part 'model/create_project_api_key_request.dart';
part 'model/create_project_body.dart';
part 'model/create_project_branding.dart';
part 'model/create_project_invite.dart';
part 'model/create_recovery_code_for_identity_body.dart';
part 'model/create_recovery_link_for_identity_body.dart';
part 'model/create_relationship_body.dart';
part 'model/create_subscription_body.dart';
part 'model/custom_domain.dart';
part 'model/custom_domain_quota.dart';
part 'model/delete_my_sessions_count.dart';
part 'model/error_authenticator_assurance_level_not_satisfied.dart';
part 'model/error_browser_location_change_required.dart';
part 'model/error_flow_replaced.dart';
part 'model/error_generic.dart';
part 'model/error_o_auth2.dart';
part 'model/expanded_permission_tree.dart';
part 'model/flow_error.dart';
part 'model/generic_error.dart';
part 'model/generic_error_content.dart';
part 'model/get_managed_identity_schema_location.dart';
part 'model/get_version200_response.dart';
part 'model/health_not_ready_status.dart';
part 'model/health_status.dart';
part 'model/identity.dart';
part 'model/identity_credentials.dart';
part 'model/identity_credentials_oidc.dart';
part 'model/identity_credentials_oidc_provider.dart';
part 'model/identity_credentials_password.dart';
part 'model/identity_credentials_type.dart';
part 'model/identity_schema_container.dart';
part 'model/identity_schema_preset.dart';
part 'model/identity_state.dart';
part 'model/identity_with_credentials.dart';
part 'model/identity_with_credentials_oidc.dart';
part 'model/identity_with_credentials_oidc_config.dart';
part 'model/identity_with_credentials_oidc_config_provider.dart';
part 'model/identity_with_credentials_password.dart';
part 'model/identity_with_credentials_password_config.dart';
part 'model/internal_get_project_branding_body.dart';
part 'model/internal_is_owner_for_project_by_slug_body.dart';
part 'model/internal_provision_mock_subscription.dart';
part 'model/introspected_o_auth2_token.dart';
part 'model/invite_quota.dart';
part 'model/is_owner_for_project_by_slug.dart';
part 'model/is_ready200_response.dart';
part 'model/is_ready503_response.dart';
part 'model/json_patch.dart';
part 'model/json_web_key.dart';
part 'model/json_web_key_set.dart';
part 'model/keto_namespace.dart';
part 'model/login_flow.dart';
part 'model/logout_flow.dart';
part 'model/managed_identity_schema.dart';
part 'model/managed_identity_schema_validation_result.dart';
part 'model/message.dart';
part 'model/message_dispatch.dart';
part 'model/namespace.dart';
part 'model/needs_privileged_session_error.dart';
// part 'model/normalized_project.dart';
// part 'model/normalized_project_revision.dart';
// part 'model/normalized_project_revision_hook.dart';
// part 'model/normalized_project_revision_identity_schema.dart';
// part 'model/normalized_project_revision_third_party_provider.dart';
part 'model/null_plan.dart';
part 'model/o_auth2_client.dart';
part 'model/o_auth2_client_token_lifespans.dart';
part 'model/o_auth2_consent_request.dart';
part 'model/o_auth2_consent_request_open_id_connect_context.dart';
part 'model/o_auth2_consent_session.dart';
part 'model/o_auth2_consent_session_expires_at.dart';
part 'model/o_auth2_login_request.dart';
part 'model/o_auth2_logout_request.dart';
part 'model/o_auth2_redirect_to.dart';
part 'model/o_auth2_token_exchange.dart';
part 'model/oidc_configuration.dart';
part 'model/oidc_user_info.dart';
part 'model/pagination.dart';
part 'model/pagination_headers.dart';
part 'model/parse_error.dart';
part 'model/perform_native_logout_body.dart';
part 'model/post_check_permission_body.dart';
part 'model/post_check_permission_or_error_body.dart';
part 'model/project.dart';
part 'model/project_api_key.dart';
part 'model/project_branding.dart';
part 'model/project_branding_colors.dart';
part 'model/project_branding_theme.dart';
part 'model/project_host.dart';
part 'model/project_invite.dart';
part 'model/project_metadata.dart';
part 'model/project_service_identity.dart';
part 'model/project_service_o_auth2.dart';
part 'model/project_service_permission.dart';
part 'model/project_services.dart';
part 'model/quota_branding_themes.dart';
part 'model/recovery_code_for_identity.dart';
part 'model/recovery_flow.dart';
part 'model/recovery_flow_state.dart';
part 'model/recovery_identity_address.dart';
part 'model/recovery_link_for_identity.dart';
part 'model/registration_flow.dart';
part 'model/reject_o_auth2_request.dart';
part 'model/relation_query.dart';
part 'model/relationship.dart';
part 'model/relationship_namespaces.dart';
part 'model/relationship_patch.dart';
part 'model/relationships.dart';
part 'model/schema_patch.dart';
part 'model/self_service_flow_expired_error.dart';
part 'model/session.dart';
part 'model/session_authentication_method.dart';
part 'model/session_caching_quota.dart';
part 'model/session_device.dart';
part 'model/set_active_project_in_console_body.dart';
part 'model/set_custom_domain_body.dart';
part 'model/set_project.dart';
part 'model/set_project_branding_theme_body.dart';
part 'model/settings_flow.dart';
part 'model/settings_flow_state.dart';
part 'model/source_position.dart';
part 'model/stripe_customer.dart';
part 'model/subject_set.dart';
part 'model/subscription.dart';
part 'model/successful_native_login.dart';
part 'model/successful_native_registration.dart';
part 'model/successful_project_update.dart';
part 'model/token_pagination.dart';
part 'model/token_pagination_headers.dart';
part 'model/token_pagination_request_parameters.dart';
part 'model/token_pagination_response_headers.dart';
part 'model/trust_o_auth2_jwt_grant_issuer.dart';
part 'model/trusted_o_auth2_jwt_grant_issuer.dart';
part 'model/trusted_o_auth2_jwt_grant_json_web_key.dart';
part 'model/ui_container.dart';
part 'model/ui_node.dart';
part 'model/ui_node_anchor_attributes.dart';
part 'model/ui_node_attributes.dart';
part 'model/ui_node_image_attributes.dart';
part 'model/ui_node_input_attributes.dart';
part 'model/ui_node_meta.dart';
part 'model/ui_node_script_attributes.dart';
part 'model/ui_node_text_attributes.dart';
part 'model/ui_text.dart';
part 'model/update_identity_body.dart';
part 'model/update_login_flow_body.dart';
part 'model/update_login_flow_with_lookup_secret_method.dart';
part 'model/update_login_flow_with_oidc_method.dart';
part 'model/update_login_flow_with_password_method.dart';
part 'model/update_login_flow_with_totp_method.dart';
part 'model/update_login_flow_with_web_authn_method.dart';
part 'model/update_recovery_flow_body.dart';
part 'model/update_recovery_flow_with_code_method.dart';
part 'model/update_recovery_flow_with_link_method.dart';
part 'model/update_registration_flow_body.dart';
part 'model/update_registration_flow_with_oidc_method.dart';
part 'model/update_registration_flow_with_password_method.dart';
part 'model/update_registration_flow_with_web_authn_method.dart';
part 'model/update_settings_flow_body.dart';
part 'model/update_settings_flow_with_lookup_method.dart';
part 'model/update_settings_flow_with_oidc_method.dart';
part 'model/update_settings_flow_with_password_method.dart';
part 'model/update_settings_flow_with_profile_method.dart';
part 'model/update_settings_flow_with_totp_method.dart';
part 'model/update_settings_flow_with_web_authn_method.dart';
part 'model/update_subscription_body.dart';
part 'model/update_verification_flow_body.dart';
part 'model/update_verification_flow_with_code_method_body.dart';
part 'model/update_verification_flow_with_link_method.dart';
part 'model/verifiable_identity_address.dart';
part 'model/verification_flow.dart';
part 'model/verification_flow_state.dart';
part 'model/version.dart';
part 'model/warning.dart';

const _delimiters = {'csv': ',', 'ssv': ' ', 'tsv': '\t', 'pipes': '|'};
const _dateEpochMarker = 'epoch';
final _dateFormatter = DateFormat('yyyy-MM-dd');
final _regList = RegExp(r'^List<(.*)>$');
final _regSet = RegExp(r'^Set<(.*)>$');
final _regMap = RegExp(r'^Map<String,(.*)>$');

ApiClient defaultApiClient = ApiClient();
